### ISSUE TITLE
can't batch-percolator after restart elasticsearch

### ISSUE THREAD

**Issue by namtran3005** [meltwater/elasticsearch-batch-percolator#5]
Hi I using elasticsearch-batch-percolator 1.0.1 version with elasticsearch version 1.7.1. It working great with a good performance. But everytime I restart elasticsearch, batch percolate can't match docs anymore. The index contain queries still there and I still can query query docs but now call percolate api will always match no docs.
I have to reindex "query docs" to make it work again.

**Comment by vorce** [comment]
Hey @namtran3005! I think you are bumping into an issue documented in the [RecoveryTests](https://github.com/meltwater/elasticsearch-batch-percolator/blob/master/src/test/java/org/elasticsearch/test/integration/RecoveryTests.java#L31). Sadly we do not have a fix for that afaik.

**Comment by spier** [comment]
Archiving this repo. Closing all Issues.
