### ISSUE TITLE
support elasticsearch 2.0

### ISSUE THREAD

**Issue by namtran3005** [meltwater/elasticsearch-batch-percolator#6]
Please support elasticsearch version 2.0

**Comment by bergetp** [comment]
Hi,
At this moment we cannot give a specific completion date, but we're actively working on the 2.x update (which requires major refactoring).

**Comment by llytvynenko** [comment]
Guys, are there any updates on the topic?

**Comment by bergetp** [comment]
@llytvynenko Sorry to say but this has been postponed for a while. The project is under way, but unfortunately it's not up to our standards yet. We are in the midst of upgrading our elastic stack (which as you probably know is a pain for large projects).

Again, apologies for the delay.

**Comment by jzillioux** [comment]
Any updates on supporting newer versions of elasticsearch?

**Comment by spier** [comment]
Archiving this repo. Closing all Issues.
